
trigger:
- master
variables:
  #Azure containter Registry name 
  acr_container_name: 'acrraghebspringimages'
  #Azure App service Plan for staging name
  app_service_plan: 'aspraghebspringplan'
  #Azure Resource group name
  varResoursegroupname: 'raghebspringrg'
  #Azyre mysql server name
  mysqlsever_name: 'raghebspringsqlserver'
  #azure web app name for staging environemnt
  Webapp_Name: 'raghebspringbootreactapp'
  #azure Kubernets Cluster name
  AKSClustername: 'raghebspringakscluster'
  #Service Connections name
  AZ_ServiceConn: 'Arm-ServiceConnection'
  AKS_ServiceConn: 'AKSClusterConnection'
  ACR_ServiceConn: 'ACRConnection'     
  #my sql database name
  mysqldb: 'employee_prod'
  VSTS_ARM_REST_IGNORE_SSL_ERRORS: true
  arm_outoput: ''




stages:
- stage: Build
  displayName: 'build the IOC image registry and empty SQL'
  jobs:
  - deployment: buildIOC
    displayName: deploy the infrastructure
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
         steps: 
           - checkout: self
           -   task: "AzureResourceGroupDeployment@2"
               inputs:
                azureSubscription: $(AZ_ServiceConn)
                action: 'Create Or Update Resource Group'
                resourceGroupName: $(varResoursegroupname)
                location: 'Central US'
                templateLocation: 'URL of the file'
                csmFileLink: 'https://raw.githubusercontent.com/moragheb/react-and-spring-data-rest/master/Environemnet%20ARM%20Template/template.json'
                deploymentMode: 'Incremental'
                csmParametersFile: https://raw.githubusercontent.com/moragheb/react-and-spring-data-rest/master/Environemnet%20ARM%20Template/template.json'
                overrideParameters: '-ACRContainer $(acr_container_name) -MYSQLServerName $(mysqlsever_name)'
                deploymentOutputs: arm_outoput
- stage: Compile
  displayName: 'build the code base and code coverage-docker and K8s files'
  dependsOn: []
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: compile
    steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            options: 'clean'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            codeCoverageToolOption: 'Cobertura'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            codeCoverageSourceDirectories: src/main    

        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
          inputs:
            SourceFolder: '$(system.defaultworkingdirectory)'
            Contents: '**/*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
          condition: succeededOrFailed()
        
        - task: PublishBuildArtifacts@1
          displayName: 'public the Kubernettes manifest file'
          inputs:
            PathtoPublish: '$(Pipeline.Workspace)/s/Kubernetes'
            ArtifactName: 'manifests'
          condition: succeededOrFailed()   
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Package-build'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: 'Package-build'
          condition: succeededOrFailed()    
- stage: Dockerbuild
  displayName: 'build the docker image and push to  Azure Container registry'
  dependsOn: 
  - 'Build'
  - 'Compile'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: dockerpush
    steps:
        - task: Docker@1
          displayName: 'build an image'
          inputs:
            azureSubscriptionEndpoint: $(AZ_ServiceConn)
            azureContainerRegistry: $(acr_container_name).azurecr.io
            dockerFile: Dockerfile
            imageName: 'SpringAppImage'
            includeLatestTag: true
            useDefaultContext: false
            buildContext: .

        - task: Docker@1
          displayName: 'Push Image'
          inputs:
            azureSubscriptionEndpoint: $(AZ_ServiceConn)
            azureContainerRegistry: $(acr_container_name).azurecr.io
            command: 'Push an image'
            imageName: 'SpringAppImage'
- stage: Stagingwebapp
  displayName: 'Deploy image to stage web app'
  dependsOn: 'Dockerbuild'
  jobs:
  - deployment: 'buildstagewebapp'
    displayName: 'deploy the stage web app'
    pool:
      vmImage: 'windows-latest'
    environment: 'stage'
    strategy:
      runOnce:
        deploy:
         steps: 
           - checkout: self
           -   task: AzureCLI@2
               inputs:
                azureSubscription: 'Arm-ServiceConnection'
                addSpnToEnvironment: true
                scriptType: ps
                scriptLocation: 'inlineScript'
                inlineScript: |
                  #create the web service plan
                  $ARM_CLIENT_ID=$servicePrincipalId
                  az appservice plan create --name $(app_service_plan) --resource-group $(varResoursegroupname)  --is-linux --sku S1
                  #set the auto Scale on the  app service plan
                  az monitor autoscale create  --resource-group $(varResoursegroupname) --resource $(app_service_plan) --resource-type Microsoft.Web/serverFarms --name autoscale --count 2 --min-count 2 --max-count 5 --count 2
                  az monitor autoscale rule create  --resource-group $(varResoursegroupname) --autoscale-name autoscale  --condition "CpuPercentage > 70 avg 10m" --scale out 3
                  az monitor autoscale rule create  --resource-group $(varResoursegroupname) --autoscale-name autoscale  --condition "CpuPercentage < 30  avg 10m" --scale in 1
                  
                  #create the Web App
                  az webapp create --resource-group $(varResoursegroupname) --plan $(app_service_plan) --name $(Webapp_Name) --deployment-container-image-name $(acr_container_name).azurecr.io/springappimage:latest
                  
                  #create the Deployment Slot
                  az webapp deployment slot create --name $(Webapp_Name) --resource-group $(varResoursegroupname) --slot staging
                  
                  #set the web app ruunning port
                  az webapp config appsettings set --resource-group $(varResoursegroupname) --name $(Webapp_Name) --settings WEBSITES_PORT=8080

                  #use the system manged identity to reach the image in the image registry
                  $SubscriptionID = az account show --query id -o tsv
                  #$principal_ID=az webapp identity assign --resource-group $(varResoursegroupname) --name $(Webapp_Name) --query principalId -o tsv 
                  az role assignment create --assignee $ARM_CLIENT_ID --scope /subscriptions/$SubscriptionID/resourceGroups/$(varResoursegroupname)/providers/Microsoft.ContainerRegistry/registries/acrspringbootimages --role "AcrPull"
                  az resource update --ids /subscriptions/$SubscriptionID/resourceGroups/$(varResoursegroupname)/providers/Microsoft.Web/sites/$(Webapp_Name)/config/web --set properties.acrUseManagedIdentityCreds=True
                  #pull the image and deploy it 
                  az webapp config container set  --name $(Webapp_Name) --resource-group $(varResoursegroupname) --docker-custom-image-name $(acr_container_name).azurecr.io/springappimage:latest --docker-registry-server-url https://$(acr_container_name).azurecr.io
- stage: createproductionencironemnt
  displayName: 'create production AKS CLuster and grant it access to the registry'
  dependsOn: 'Stagingwebapp'
  jobs:
  - deployment: 'buildtheAKSCluster'
    displayName: 'deploy the prod environemnt'
    pool:
      vmImage: 'windows-latest'
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
         steps: 
           - checkout: self
           -   task: "AzureCLI@2"
               inputs:
                  azureSubscription: $(AZ_ServiceConn)
                  scriptType: ps
                  addSpnToEnvironment: true
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                      #create an AKS Cluster
                      $ARM_CLIENT_ID=$servicePrincipalId 
                      $ARM_CLIENT_Key=$servicePrincipalKey
                      az aks create --resource-group $(varResoursegroupname) --name $(AKSClustername) --node-count 1 --enable-addons monitoring --generate-ssh-keys
                      az aks update -n $(AKSClustername) -g $(varResoursegroupname) --attach-acr $(acr_container_name)
                      #create the SQL DB
                      az mysql db create --name $(mysqldb) --resource-group $(varResoursegroupname)  --server-name $(mysqlsever_name)
                      #create SPN to access the ACR
                      $ACR_REGISTRY_ID=$(az acr show --name $(acr_container_name) --query id --output tsv)                      
                      #az role assignment create --assignee $ARM_CLIENT_ID --scope $ACR_REGISTRY_ID --role acrpull
                   
- stage: deployimagetoAKSanddacpactosql
  displayName: 'deploy to AKS cluser and upload the DACPAC to the mysqldb'
  dependsOn: 'createproductionencironemnt'
  variables:
     $ImagePullSecret: "K8ssecret"
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: 'deployapptoAKS'
    displayName: 'deploy the AKS Cluster'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
         steps: 
           - checkout: self
        
           - task:  "KubernetesManifest@0"
             displayName: "Create an image pull secret"
             inputs:
               action:  "createSecret"
               kubernetesServiceConnection: $(AKS_ServiceConn)
               namespace: "default"
               secretName: '$ACRSecret'
               secretType: 'dockerRegistry'
               dockerRegistryEndpoint: $(ACR_ServiceConn)  
           - task  : "KubernetesManifest@0"
             displayName: Deploy to Kubernetes cluster
             inputs:
              action: deploy
              namespace: "default"
              imagePullSecrets: 
              secretName: $(ImagePullSecret)
              name: $(ImagePullSecret)
              kubernetesServiceConnection: $(AKS_ServiceConn)
              manifests: |
                $(Pipeline.Workspace)/manifests/reactandspringdatarest-deployment.yml
                $(Pipeline.Workspace)/manifests/reactandspringdatarest-service.yml
              containers: |
                $(acr_container_name)/"SpringAppImage:latest" 



                        
                  